language: c

dist: xenial

addons:
  apt:
    packages:
      - astyle
      - perltidy
      - python-pip
      - gcc-multilib

install:
  - sudo pip install yapf

script:
  - tools/check-syntax -f && git diff --exit-code
  - make
